import { Router } from "express";
import { GoogleGenAI } from "@google/genai";
import { db } from "@workspace/db";
import { analysesTable } from "@workspace/db";
import { desc, sql, eq } from "drizzle-orm";
import { AnalyzeContentBody, GetEmergencyActionsBody } from "@workspace/api-zod";

const router = Router();

const ai = new GoogleGenAI({ apiKey: process.env.GOOGLE_GEMINI_API_KEY || "" });

// ─── POST /analyze ────────────────────────────────────────────────────────────
router.post("/analyze", async (req, res) => {
  const parsed = AnalyzeContentBody.safeParse(req.body);
  if (!parsed.success) {
    res.status(400).json({ error: "content is required" });
    return;
  }

  const { content } = parsed.data;
  const urlRegex = /https?:\/\/[^\s]+/i;
  const isUrl = urlRegex.test(content.trim());

  try {
    const urlBlock = isUrl ? `
9. URL INTELLIGENCE: analyze the URL.
   - Extract domain
   - Detect typosquatting (amaz0n, paypa1, etc.)
   - Detect URL shortener (bit.ly, tinyurl, t.co, etc.)
   - List suspicious path/param keywords
   - URL threat score 0-100
   Include: "urlIntelligence": { "isUrl": true, "domain": "...", "threatScore": N, "possibleTyposquatting": bool, "typosquattingTarget": "brand or empty", "usesUrlShortener": bool, "suspiciousKeywords": [], "recommendation": "one sentence" }

10. DOMAIN COMPARISON: If the URL appears to impersonate a known brand/institution (India Post, SBI, HDFC, PayPal, Amazon, etc.):
   Include: "domainComparison": { "detected": true, "submittedDomain": "the-fake-domain.com", "officialDomain": "indiapost.gov.in", "isOfficial": false, "brand": "India Post" }
   If no impersonation detected: "domainComparison": { "detected": false, "submittedDomain": "...", "officialDomain": "", "isOfficial": true, "brand": "" }` :
    `Include: "urlIntelligence": { "isUrl": false, "domain": "", "threatScore": 0, "possibleTyposquatting": false, "typosquattingTarget": "", "usesUrlShortener": false, "suspiciousKeywords": [], "recommendation": "" }, "domainComparison": { "detected": false, "submittedDomain": "", "officialDomain": "", "isOfficial": true, "brand": "" }`;

    const prompt = `You are the ScamShield AI Agent. Analyze the provided input — it may be a text message, email, URL, QR code content, social media post, job listing, or any communication used in a scam.

INPUT TO ANALYZE:
"${content.replace(/"/g, '\\"')}"

ANALYSIS STEPS:
1. Identify medium/format (SMS, email, URL, job post, QR redirect, etc.)
2. Categorize scam type. If legitimate, say "Legitimate".
3. Evaluate risk level (Low/Medium/High/Critical) and confidence score 0-100. Use precise numbers like 73 or 91, not round numbers.
4. Analyze psychological triggers: Urgency, Authority, Scarcity, Fear, Emotional Manipulation, Greed.
5. Identify vulnerable demographic groups.
6. Break down the scammer's step-by-step attack chain.
7. Write an ELI15 summary in plain, friendly language (2-3 sentences).
8. AI-GENERATED CONTENT LIKELIHOOD: Assess whether this message was likely generated by AI.
   Signals: generic/formal wording, professional tone despite suspicious content, mass-targeting phrasing, lack of personal details, unnaturally perfect grammar.
   Include: "aiGeneratedLikelihood": { "likelihood": "Low"|"Moderate"|"High", "reasons": ["reason1", "reason2"], "disclaimer": "This is an estimate and not proof of AI generation." }
${urlBlock}
11. REPORTING LINKS: Based on the scam type and context, provide 3-5 relevant reporting destinations.
   Examples: cybercrime.gov.in for any cybercrime, TRAI DND for spam calls, LinkedIn for job scams, specific bank fraud helplines, India Post for postal fraud, SEBI for investment fraud.
   Include: "reportingLinks": [ { "platform": "Cyber Crime Portal", "url": "https://cybercrime.gov.in", "description": "Report to National Cyber Crime Reporting Portal" }, ... ]

RETURN ONLY VALID JSON (no markdown, no code blocks):
{
  "type": "scam category",
  "riskLevel": "Low"|"Medium"|"High"|"Critical",
  "confidenceScore": number,
  "reasoning": ["3-5 specific red flag observations"],
  "recommendedActions": ["3-5 concrete actions"],
  "preventionTips": ["3-4 prevention tips"],
  "eli15": "plain English explanation",
  "vulnerableGroups": ["group1", "group2"],
  "scammerStrategy": ["Step 1: ...", "Step 2: ...", "Step 3: ..."],
  "educationMode": {
    "techniques": [
      { "name": "Urgency", "detected": bool, "explanation": "one sentence" },
      { "name": "Authority", "detected": bool, "explanation": "one sentence" },
      { "name": "Scarcity", "detected": bool, "explanation": "one sentence" },
      { "name": "Fear", "detected": bool, "explanation": "one sentence" },
      { "name": "Emotional Manipulation", "detected": bool, "explanation": "one sentence" },
      { "name": "Greed Appeal", "detected": bool, "explanation": "one sentence" }
    ],
    "whyThisMatters": "one sentence"
  },
  "urlIntelligence": { ... },
  "domainComparison": { ... },
  "aiGeneratedLikelihood": { ... },
  "reportingLinks": [ ... ]
}`;

    const response = await ai.models.generateContent({
      model: "gemini-2.5-flash",
      contents: [{ role: "user", parts: [{ text: prompt }] }],
      config: {
        responseMimeType: "application/json",
        temperature: 0.1,
        maxOutputTokens: 8192,
      },
    });

    const rawText = response.text ?? "{}";
    let result;
    try {
      result = JSON.parse(rawText);
    } catch {
      res.status(500).json({ error: "Failed to parse AI response" });
      return;
    }

    const snippet = content.slice(0, 200) + (content.length > 200 ? "..." : "");
    await db.insert(analysesTable).values({
      contentSnippet: snippet,
      riskLevel: result.riskLevel ?? "Low",
      scamType: result.type ?? "Unknown",
      confidenceScore: result.confidenceScore ?? 0,
      fullResult: JSON.stringify(result),
    });

    res.json(result);
  } catch (err) {
    req.log.error({ err }, "Gemini analysis failed");
    res.status(500).json({ error: "AI analysis failed. Please try again." });
  }
});

// ─── POST /emergency ──────────────────────────────────────────────────────────
router.post("/emergency", async (req, res) => {
  const parsed = GetEmergencyActionsBody.safeParse(req.body);
  if (!parsed.success) {
    res.status(400).json({ error: "exposures array is required" });
    return;
  }

  const { exposures, scamContext } = parsed.data;

  const exposureDescriptions: Record<string, string> = {
    otp: "shared an OTP (one-time password)",
    bank_details: "shared bank account details or card numbers",
    installed_app: "installed an app from the scammer",
    scanned_qr: "scanned a QR code that may have redirected to a malicious site",
    sent_money: "sent money to the scammer",
    shared_password: "shared a password or login credentials",
    clicked_link: "clicked a suspicious link",
  };

  const exposureList = exposures
    .map((e) => exposureDescriptions[e] || e)
    .join(", ");

  const prompt = `You are a cybersecurity emergency response expert. A user has just fallen for a scam.

WHAT HAPPENED:
- Exposures: ${exposureList}
${scamContext ? `- Scam context: ${scamContext}` : ""}

Generate an IMMEDIATE recovery action plan. Be concise, calm, and actionable. Every minute matters.

Assess overall severity: "moderate" (no financial/credential exposure), "serious" (credentials exposed), or "critical" (money sent or banking details shared).

RETURN ONLY VALID JSON (no markdown):
{
  "severity": "moderate"|"serious"|"critical",
  "summary": "2-sentence calm reassurance + what to do first",
  "actions": [
    {
      "priority": "immediate",
      "title": "short action title",
      "description": "specific instructions",
      "timeframe": "Do this now / Within 30 minutes / Within 24 hours"
    }
  ],
  "hotlines": ["India: Cyber Crime Helpline 1930", "India: Bank customer care (call number on your card)", "Emergency: 112"]
}

Rules:
- "immediate" priority: next 5 minutes
- "urgent" priority: next hour
- "soon" priority: today
- Include 5-8 actions total, ordered by priority
- Be specific about what to do and who to call
- Include the most relevant Indian helplines`;

  try {
    const response = await ai.models.generateContent({
      model: "gemini-2.5-flash",
      contents: [{ role: "user", parts: [{ text: prompt }] }],
      config: {
        responseMimeType: "application/json",
        temperature: 0.1,
        maxOutputTokens: 4096,
      },
    });

    const rawText = response.text ?? "{}";
    let result;
    try {
      result = JSON.parse(rawText);
    } catch {
      res.status(500).json({ error: "Failed to parse emergency response" });
      return;
    }

    res.json(result);
  } catch (err) {
    req.log.error({ err }, "Emergency route failed");
    res.status(500).json({ error: "Failed to generate emergency plan. Please try again." });
  }
});

// ─── GET /history ─────────────────────────────────────────────────────────────
router.get("/history", async (req, res) => {
  try {
    const records = await db
      .select({
        id: analysesTable.id,
        contentSnippet: analysesTable.contentSnippet,
        riskLevel: analysesTable.riskLevel,
        scamType: analysesTable.scamType,
        confidenceScore: analysesTable.confidenceScore,
        analyzedAt: analysesTable.analyzedAt,
      })
      .from(analysesTable)
      .orderBy(desc(analysesTable.analyzedAt))
      .limit(50);

    res.json(
      records.map((r) => ({
        ...r,
        analyzedAt: r.analyzedAt.toISOString(),
      }))
    );
  } catch (err) {
    req.log.error({ err }, "Failed to fetch history");
    res.status(500).json({ error: "Failed to fetch history" });
  }
});

// ─── DELETE /history/:id ──────────────────────────────────────────────────────
router.delete("/history/:id", async (req, res) => {
  const id = parseInt(req.params.id, 10);
  if (isNaN(id)) {
    res.status(400).json({ error: "Invalid id" });
    return;
  }

  try {
    const deleted = await db
      .delete(analysesTable)
      .where(eq(analysesTable.id, id))
      .returning({ id: analysesTable.id });

    if (deleted.length === 0) {
      res.status(404).json({ error: "Record not found" });
      return;
    }

    res.json({ success: true });
  } catch (err) {
    req.log.error({ err }, "Failed to delete history record");
    res.status(500).json({ error: "Failed to delete record" });
  }
});

// ─── GET /stats ───────────────────────────────────────────────────────────────
router.get("/stats", async (req, res) => {
  try {
    const [totalRow] = await db
      .select({ count: sql<number>`count(*)::int` })
      .from(analysesTable);

    const byRiskRows = await db
      .select({
        riskLevel: analysesTable.riskLevel,
        count: sql<number>`count(*)::int`,
      })
      .from(analysesTable)
      .groupBy(analysesTable.riskLevel);

    const byTypeRows = await db
      .select({
        scamType: analysesTable.scamType,
        count: sql<number>`count(*)::int`,
      })
      .from(analysesTable)
      .groupBy(analysesTable.scamType)
      .orderBy(desc(sql`count(*)`))
      .limit(10);

    const [avgRow] = await db
      .select({ avg: sql<number>`avg(confidence_score)::float` })
      .from(analysesTable);

    const byRiskLevel: Record<string, number> = {};
    for (const row of byRiskRows) byRiskLevel[row.riskLevel] = row.count;

    const byType: Record<string, number> = {};
    for (const row of byTypeRows) byType[row.scamType] = row.count;

    res.json({
      totalAnalyzed: totalRow?.count ?? 0,
      byRiskLevel,
      byType,
      averageConfidence: Math.round(avgRow?.avg ?? 0),
    });
  } catch (err) {
    req.log.error({ err }, "Failed to fetch stats");
    res.status(500).json({ error: "Failed to fetch stats" });
  }
});

export default router;
